version: '3'
services:
  php:
    build: ./docker/php-fpm
    ports:
     - "9000:9000"
     - "9501:9501"
    volumes:
     - ./docker/supervisord:/etc/supervisor.d
     - ./src:/var/www/src
  nginx:
    build: ./docker/nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./src:/var/www/src
     - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
     - php